name: Build and deploy

on:
  # Triggers the workflow on push event but only for the "master" branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: Set up JDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          
      - name: Build with gradle
        run: gradle build